django_app/converter/urls.py
from django.urls import path
from . import views

app_name = 'converter'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),  # просмотр главной страницы
    path('register/', views.RegisterUser.as_view(), name='register'),  # регистрация
    path('login/', views.LoginUser.as_view(), name='login'),  # аутентификация
    path('logout/', views.LogoutUser.as_view(), name='logout'),  # выход из приложения
    path('converter/', views.Converter.as_view(), name='converter'),  # заполнение формы для конвертера

]

django_app/django_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('converter.urls', namespace='converter')),
]

django_app/converter/models.py
from django.db import models


# Create your models here.

class DateConverter(models.Model):
    date_json = models.TextField(help_text='Строка с данными из запроса к API в виде строки json',
                                 verbose_name="Данные для конвертации")

django_app/converter/forms.py
from django import forms

currency_type = [
    ("USD", "доллар"),
    ("RUB", "рубль"),
    ("EUR", "евро"),

]


class ConverterForm(forms.Form):
    query_type_input = forms.ChoiceField(label="ваша валюта", choices=currency_type)
    query_type_output = forms.ChoiceField(label="перевод валюты", choices=currency_type)
    sum_of_money = forms.IntegerField(label="денежная сумма")

django_app/converter/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView

import json
from . import forms
from . import currency_converter
from . import models


# Create your views here.

class Index(TemplateView):
    '''
    Стартовая страница приложения converter
    '''
    template_name = "converter/index.html"


class RegisterUser(CreateView):
    '''
    Страница регистрации в приложении converter
    '''
    form_class = UserCreationForm
    template_name = "converter/register.html"
    success_url = reverse_lazy("converter:login")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        """
        При успешной регистрации автоматически проводим аутентификацию
        и переходим на главную страницу приложения
        :param form:
        :return:
        """
        user = form.save()
        login(self.request, user)
        return redirect("converter:index")


class LoginUser(LoginView):
    '''
    Страница аутентификации в приложении converter
    '''
    form_class = AuthenticationForm
    template_name = "converter/login.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_success_url(self):
        return reverse_lazy("converter:index")


class LogoutUser(LogoutView):
    """
    Выход из идентификации пользователя
    """
    template_name = "converter/index.html"


class Converter(View):
    '''
    Заполнение формы для конвертера
    '''

    def get(self, request):
        form = forms.ConverterForm
        template_name = "converter/converter.html"
        context = {"form": form}
        return render(request=request,
                      template_name=template_name,
                      context=context)

    def post(self, request):
        model = models.DateConverter
        all_dates = model.objects.all()
        api_dict_today = json.loads(all_dates[0].date_json)

        template_name = "converter/result.html"
        form = forms.ConverterForm(request.POST)
        context = {}
        if form.is_valid():
            data = form.cleaned_data
            context["query_type_input"] = data.get("query_type_input")  # основная валюта
            context["query_type_output"] = data.get("query_type_output")  # валюта для перевода
            context["sum_of_money"] = data.get("sum_of_money")  # сумма исходная
            result = currency_converter.ParserCalculateConverter(
                query_type_input=context["query_type_input"],
                query_type_output=context["query_type_output"],
                sum_of_money=context["sum_of_money"],
                data_dict=api_dict_today,
            )()
            context["sum_of_result"] = round(result, 2)

        return render(request=request,
                      template_name=template_name,
                      context=context)

django_app/converter/templates/converter/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block css %} {% endblock %}
</head>
<body>

<div class="navbar">
    {% include 'includes/topbar.html' %}
</div>

{% block content %} {% endblock %}

<div class="navbar" >
    {% include 'includes/navbar.html' %}
</div>

</body>
</html>

django_app/converter/templates/converter/converter.html
{% extends 'converter/base.html'  %}
{% load static %}


{% block title %}заполнение формы запроса{% endblock %}

{% block content %}
<div>
    <h1>Выберете валюту и сумму для конвертации</h1>
</div>
<div class="card-base">
    <form action="" method="post">
        {% csrf_token %}
        <ul>
            {% for field in form %}
            <li>{{ field.label }} {{ field }}</li><br>
            {% endfor %}
        </ul>
        <div>
            <button type="submit" value="тип запроса">отправить запрос</button>
            |
            <button type="reset">очистить форму</button>
        </div>
    </form>
</div>
{% endblock %}

django_app/converter/templates/converter/index.html
{% extends 'converter/base.html'  %}
{% load static %}


{% block title %}Стартовая страница приложения{% endblock %}

{% block content %}
<div>
    <h1>Стартовая страница приложения корвертера валют</h1>
</div>
{% endblock %}

django_app/converter/templates/converter/login.html
{% extends 'converter/base.html'  %}
{% load static %}


{% block title %}Cтраница аутентификации в приложении{% endblock %}

{% block content %}
<div>
    <h1>Страница аутентификации в приложении конвертера валют</h1>
</div>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти в приложение</button>
</form>


{% endblock %}

django_app/converter/templates/converter/register.html
{% extends 'converter/base.html'  %}
{% load static %}


{% block title %}Cтраница регистрации приложения{% endblock %}

{% block content %}
<div>
    <h1>Страница регистрации в приложении конвертера валют</h1>
</div>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться в приложении</button>
</form>


{% endblock %}

django_app/converter/templates/converter/result.html
{% extends 'converter/base.html'  %}
{% load static %}


{% block title %}результат запроса{% endblock %}

{% block content %}
<div>
    <h1>Результат запроса</h1>
</div>
<div class="card-base">
    <ul>
        <li>Базовая валюта: {{ query_type_input }} | денежная сумма: {{ sum_of_money }}</li>
        <li>Валюта для перевода: {{ query_type_output }} | денежная сумма: {{ sum_of_result }}</li>

    </ul>
</div>
{% endblock %}

django_app/converter/templates/includes/navbar.html
<a href="{% url 'converter:index' %}">возврат на главную страницу</a> |
<a href="{% url 'converter:converter' %}">заполнение формы для конвертера</a>

django_app/converter/templates/includes/topbar.html
{% if request.user.is_authenticated %}
    <a>пользователь: {{user.username}}</a> |
    <a href="{% url 'converter:logout' %}">выход</a>
{% else %}
    <a>Вы не авторизованны</a> |
    <a href="{% url 'converter:register' %}">регистрация</a> |
    <a href="{% url 'converter:login' %}">вход</a>
{% endif %}